export const avatars = [
  { id: 1, url: "/avatars/face1.png" },
  { id: 2, url: "/avatars/face2.png" },
  { id: 3, url: "/avatars/face3.png" },
  { id: 4, url: "/avatars/face4.png" },
  { id: 5, url: "/avatars/face5.png" },
  { id: 6, url: "/avatars/face6.png" },
  { id: 7, url: "/avatars/face7.png" },
  { id: 8, url: "/avatars/face8.png" },
  { id: 9, url: "/avatars/face9.png" },
  { id: 10, url: "/avatars/face10.png" },
  { id: 11, url: "/avatars/face11.png" },
  { id: 12, url: "/avatars/face12.png" },
  { id: 13, url: "/avatars/face13.png" },
  { id: 14, url: "/avatars/face14.png" },
  { id: 15, url: "/avatars/face15.png" },
  { id: 16, url: "/avatars/face16.png" },
  { id: 17, url: "/avatars/face17.png" },
  { id: 18, url: "/avatars/face18.png" },
  { id: 19, url: "/avatars/face19.png" },
  { id: 20, url: "/avatars/face20.png" },
  { id: 21, url: "/avatars/face21.png" },
  { id: 22, url: "/avatars/face22.png" },
  { id: 23, url: "/avatars/face23.png" },
  { id: 24, url: "/avatars/face24.png" },
];
